name: speedy_delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.2+12


environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.0
  connectivity_plus: ^6.0.3
  crypto: ^3.0.3
  firebase_auth: ^5.1.2
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_cashfree_pg_sdk: ^2.1.2+32
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  pinput: ^4.0.0
  provider: ^6.1.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6

  http: any
  uuid: any
  flutter_dotenv: ^5.1.0
  flutter_phone_direct_caller: ^2.1.1
  badges: ^3.1.2
  restart_app: ^1.2.1
  path: any
  accordion: ^2.6.0
  firebase_app_check: ^0.3.0+2
  dotted_line: ^3.2.2
  flutter_native_splash: ^2.4.0
  firebase_messaging: ^15.0.2
  shimmer: ^3.0.0
  flutter_local_notifications: ^17.2.1+1
  in_app_update: ^4.2.3
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  onesignal_flutter: ^5.2.2
  mailer: ^6.1.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon.png
    - assets/images/dog.png
    - assets/images/stop.png
    - lib/.env

  fonts:
    - family: Gilroy-Black
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf

    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf

    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf

    - family: Gilroy-Heavy
      fonts:
        - asset: assets/fonts/Gilroy-Heavy.ttf

    - family: Gilroy-ExtraBold
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.ttf

    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf

    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf