// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDETzKIsnWeE4zDF2DvULMXSBoR4EPcCKY',
    appId: '1:371540153942:web:95f8b1777a7496dae00df7',
    messagingSenderId: '371540153942',
    projectId: 'speedy-app-e17a5',
    authDomain: 'speedy-app-e17a5.firebaseapp.com',
    storageBucket: 'speedy-app-e17a5.appspot.com',
    measurementId: 'G-DL3533Z2T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM1aZ9Sbt6J1yE-6m7mKF0Vrpcv0lYESE',
    appId: '1:371540153942:android:28c1f3c59b9b4a49e00df7',
    messagingSenderId: '371540153942',
    projectId: 'speedy-app-e17a5',
    storageBucket: 'speedy-app-e17a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRoiUE06tGrGqS-lYof5_tKSuZxyUDPJk',
    appId: '1:371540153942:ios:ce1c4ccfb7f22d67e00df7',
    messagingSenderId: '371540153942',
    projectId: 'speedy-app-e17a5',
    storageBucket: 'speedy-app-e17a5.appspot.com',
    iosBundleId: 'com.example.speedyDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRoiUE06tGrGqS-lYof5_tKSuZxyUDPJk',
    appId: '1:371540153942:ios:ce1c4ccfb7f22d67e00df7',
    messagingSenderId: '371540153942',
    projectId: 'speedy-app-e17a5',
    storageBucket: 'speedy-app-e17a5.appspot.com',
    iosBundleId: 'com.example.speedyDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDETzKIsnWeE4zDF2DvULMXSBoR4EPcCKY',
    appId: '1:371540153942:web:0edcb2db686360c1e00df7',
    messagingSenderId: '371540153942',
    projectId: 'speedy-app-e17a5',
    authDomain: 'speedy-app-e17a5.firebaseapp.com',
    storageBucket: 'speedy-app-e17a5.appspot.com',
    measurementId: 'G-MLW32LCN4W',
  );

}