// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkhObxIQ3B0vAcpm2yRCCuRLUQTZJR8Q0',
    appId: '1:776399631000:web:25af1a447599765febd6ed',
    messagingSenderId: '776399631000',
    projectId: 'speedy-57c76',
    authDomain: 'speedy-57c76.firebaseapp.com',
    storageBucket: 'speedy-57c76.appspot.com',
    measurementId: 'G-7NM4S32ZSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsXm1M5BpO4kdzKkx2SoSh9ikect07vew',
    appId: '1:776399631000:android:b03133bc4915dfa3ebd6ed',
    messagingSenderId: '776399631000',
    projectId: 'speedy-57c76',
    storageBucket: 'speedy-57c76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBb3bsD0k3ygUj8SUKMzlTPRQF6vthPJs',
    appId: '1:776399631000:ios:7b5dfac01fd7d8c8ebd6ed',
    messagingSenderId: '776399631000',
    projectId: 'speedy-57c76',
    storageBucket: 'speedy-57c76.appspot.com',
    androidClientId: '776399631000-2lgc2ulflpgshsce0kqm575tg6j98gf9.apps.googleusercontent.com',
    iosClientId: '776399631000-fmif45ju4otpqieddb89ia4fjdaattjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.speedyDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBb3bsD0k3ygUj8SUKMzlTPRQF6vthPJs',
    appId: '1:776399631000:ios:7b5dfac01fd7d8c8ebd6ed',
    messagingSenderId: '776399631000',
    projectId: 'speedy-57c76',
    storageBucket: 'speedy-57c76.appspot.com',
    androidClientId: '776399631000-2lgc2ulflpgshsce0kqm575tg6j98gf9.apps.googleusercontent.com',
    iosClientId: '776399631000-fmif45ju4otpqieddb89ia4fjdaattjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.speedyDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkhObxIQ3B0vAcpm2yRCCuRLUQTZJR8Q0',
    appId: '1:776399631000:web:d3439be59ac1fe8aebd6ed',
    messagingSenderId: '776399631000',
    projectId: 'speedy-57c76',
    authDomain: 'speedy-57c76.firebaseapp.com',
    storageBucket: 'speedy-57c76.appspot.com',
    measurementId: 'G-X1WS80VQ92',
  );

}